### PR TITLE
More heavy restructuring of repo

### LINKED ISSUE #10: Organization
@jgkamat can you move everything but CI and the README to a file in slides called config?

### PR DESCRIPTION
**Pull request by jgkamat**
Closes #10 

Because this is pretty nonstandard I'm gonna need to take a little bit of extra time to validate that the CI is still happy, I'm not sure if I'm doing that right.

### CODE REVIEW

**Comment by ebarnette** [comment]
Yeah CI is gonna take some heavy restructuring

**Comment by jgkamat** [comment]
I'm :+1:, hopefully the links are all good, but we won't know until we deploy :smile:

**Comment by ebarnette** [comment]
Do all of the slides still work? Are there paths that need to be changes since we changed the place the config files are in?

**Comment by jgkamat** [comment]
I changed the README too, so the links should be up to date. I won't be 100% sure until the auto-deploy takes care of it though, if it's wrong I'll submit another PR.

**Review by ebarnette — APPROVED** [review]
Fingers crossed that nothing massive breaks

**Pull request merged**
