### PR TITLE
Add CI check for linear slides

### PR DESCRIPTION
**Pull request by kberzinch**
Based on discussion with other presenters, we'd like to stick to linear slides.

(Am I doing it right?)

### CODE REVIEW

**Comment by jgkamat** [comment]
Setting `reveal-hlevel`  to `0` should give you the effect you want.

**Comment by kberzinch** [comment]
Neat! Will update.

**Review by jgkamat — APPROVED** [review]
LGTM :+1:

**Comment by jgkamat** [comment]
Also keep in mind, some slides [like this one, for example](https://raw.githubusercontent.com/RoboJackets/software-training/weekOneGitSlides/src/github.org) will continue to have nested slides because they override the project-wide setting in the file itself. It's probably a good idea to remove those headers if you don't explicily want to override project settings (although, for that example, I think that's a WIP by @chsahit).

**Comment by kberzinch** [comment]
Yeah, I think we can catch those in PR review.

**Pull request merged**
