### PR TITLE
Restructures repo. May break things.

### PR DESCRIPTION
**Pull request by ebarnette**
@jgkamat I probably broke a lot of slide things.

also TEST.org is in the code file as a placeholder

### CODE REVIEW

**Comment by ebarnette** [comment]
Also CI is going to be very broken.

**Comment by jgkamat** [comment]
@sastorer I feel like this is a bad idea right now, because I think this might cause a bunch of annoying conflicts in #4 and #5. Can we merge them as is for now, and I'll submit a PR after reorging the repo?

**Comment by ebarnette** [comment]
Yeah sure.

I want:
a) as few top level directories as possible (ideally just Slides and Code)
b) folders under both Slides and Code directories labeled by week

**Comment by jgkamat** [comment]
@sastorer sounds good, I'll plan for a 
- `./slides/1`
- `./code/1`

I'd rather stick to lowercase, since it follows the convention a bit more, but if you *really* want uppercase, I'll do it.

Also, just FYI, most of the files you moved from the root probably should to stay in the root (eg: the makefile, cask, etc), to make it super easy for newcomers to build the slides. The source files themselves (*.org, *.{c,java,py}) we can move wherever.

**Comment by kberzinch** [comment]
I vote lowercase but slide-related files in a slides folder.

**Comment by ebarnette** [comment]
@jgkamat just merged example code

Waiting on the WAI section of topic slides to merge and then you can do your reorg magic...it'll just look gross for like another day

**Comment by ebarnette** [comment]
@jgkamat You're good to do this ASAP. Just merged the topic slides from week 1.

**Pull request closed without merging**
