### PR TITLE
Week four merge

### PR DESCRIPTION
**Pull request by JasonGibson274**

### CODE REVIEW

**Review by rmkeezer — DISMISSED** [review]
LGTM

**Comment by jgkamat** [comment]
Shouldn't this be from the `weekFour` branch to master? Not `weekFourMerge`?

Or, weekFour needs to be merged into here.

**Comment by JasonGibson274** [comment]
I merged master and weekFour into this branch so week 4 does not have everything on it. I thought we wanted to keep the weeks seperate

**Review by jgkamat — APPROVED** [review]
Let's do it plz

**Review by rmkeezer — APPROVED** [review]
After running every change through a recursive deep neural network, it has conclude that it "LGTM"

**Pull request merged**
