### PR TITLE
Update README

### PR DESCRIPTION
**Pull request by jgkamat**
Links seem to be working, but the titles are screwed up (I always get something wrong).

This should fix it. 

Let me know if the links are broken for you though.

### CODE REVIEW

**Comment by ebarnette** [comment]
Github slides link at the end of the topic slides 404s for me?
Idk if that's because it's on your fork or no

EDIT: just checked, 404s on master as well

**Comment by jgkamat** [comment]
Which slides are you talking about, could you give me a link? I'm only testing the links in the readme on master, which seem to be good.

**Comment by ebarnette** [comment]
I clicked the very last link in topic slides that should take me to the gh slides and it 404s

**Comment by jgkamat** [comment]
@sastorer this link?

2017-07-05-005852_1249x809_scrot

It seems to be working for me, if you could give me the URL which you are trying to hit (and is 404'ing), I can take a closer look.

**Comment by ebarnette** [comment]
https://github.com/RoboJackets/software-training/blob/master/slides/week1/github.html

404s for me

**Comment by jgkamat** [comment]
OH, these are on the org files themselves. Whoever made that link didn't make a 'real' org link (hardcoded to `./week1.html`), so that link never would have worked. I'll see if I can fix it.

For reference, you're clicking this link right?
2017-07-05-010619_507x430_scrot

**Comment by ebarnette** [comment]
Specifically where it says to "click here for this week's Git presentation" but yes

**Comment by jgkamat** [comment]
Switching the link to a real org link should fix the issue across all exports. 

To test it out, try it here: https://github.com/jgkamat/software-training/blob/jay/README-1/slides/week1/week1.org

**Review by ebarnette — APPROVED** [review]
Assuming all links work LGTM

**Comment by ebarnette** [comment]
Confirmed works

**Comment by jgkamat** [comment]
Let me know if they don't on master soon. Issues like these shouldn't matter to the structure (and are just generic fixes like this one), so you can go ahead and begin forking and stuff now.

**Pull request merged**
